
/*  11_sequence.sql  */

/*
# 시퀀스 ( sequence )
- 테이블 내의 유일한 숫자를 자동으로 생성하는 자동 번호 생성기 입니다
- 행을 구분하는 기본키가 유일한 값을 갖도록 테이블 내의 유일한 숫자를 자동으로 생성할 수 있습니다
  CREATE SEQUENCE sequence_name
         START WITH            -> 시퀀스 번호의 시작값 지정
         INCREMENT BY          -> 연속적인 시퀀스 번호의 증가치
         MAXVALUE | NOMAXVALUE -> 최대값 지정
         MINVALUE | NOMINVALUE -> 최소값 지정
         CYCLE | NOCYCLE       -> 시퀀스가 최대값까지 완료되면 시작값에 다시 시작
         CACHE | NOCACHE       -> 메모리상의 시퀀스 값 관리
- CURRVAL : 현재값 반환
  NEXTVAL : 현재 시퀀스 값의 다음값 반환
*/

-- 시퀀스 객체 생성
CREATE SEQUENCE TEST_SEQ
START WITH 1
INCREMENT BY 1;

-- NEXTVAL 로 새로운 값을 생성
SELECT TEST_SEQ.NEXTVAL
FROM DUAL;

-- 시퀀스 객체의 현재값
SELECT TEST_SEQ.CURRVAL
FROM DUAL;

-- 시퀀스 객체 삭제
DROP SEQUENCE TEST_SEQ;

-- 연습용 테이블
DROP TABLE EMP01;

CREATE TABLE EMP01(
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10),
HIREDATE DATE
);

-- EMP01 테이블의 사원번호 적용하는 SEQUENCE 객체 생성
CREATE SEQUENCE EMP01_EMPNO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000;

-- 데이터 추가
INSERT INTO EMP01 VALUES (EMP01_EMPNO_SEQ.NEXTVAL, 'MAN_A', SYSDATE);
INSERT INTO EMP01 VALUES (EMP01_EMPNO_SEQ.NEXTVAL, 'MAN_B', SYSDATE);

SELECT * FROM EMP01;

DROP SEQUENCE EMP01_EMPNO_SEQ;


/*
# 시퀀스 수정
- ALTER SEQUENCE 는 START WITH 절 빼고, CREATE SEQUENCE 와 구조가 동일합니다
  START WITH 옵션은 변경할 수 없고, 다시 시작하려면 스퀀스를 삭제하고 다시 생성해야 합니다
*/

-- 연습용 테이블
CREATE TABLE STEST(
SNO NUMBER(2) PRIMARY KEY
);

-- STEST 테이블 SNO 컬럼에 적용할 시퀀스 객체 생성
CREATE SEQUENCE STEST_SNO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 3;

-- 데이터 추가
INSERT INTO STEST VALUES (STEST_SNO_SEQ.NEXTVAL);
INSERT INTO STEST VALUES (STEST_SNO_SEQ.NEXTVAL);
INSERT INTO STEST VALUES (STEST_SNO_SEQ.NEXTVAL);

SELECT * FROM STEST;

SELECT STEST_SNO_SEQ.CURRVAL
FROM DUAL;

-- 시퀀스 최대값 수정
ALTER SEQUENCE STEST_SNO_SEQ
MAXVALUE 10;

INSERT INTO STEST VALUES (STEST_SNO_SEQ.NEXTVAL);

SELECT * FROM STEST;

DROP SEQUENCE STEST_SNO_SEQ;

/* Quiz */

-- 부서정보를 가지는 테이블을 생성하세요 : 부서번호, 부서명, 지역
-- > 부서번호는 sequence 를 사용해서 적용합니다 ( 초기값 10, 10씩 증가 )
CREATE TABLE DEPT_TEST(
DEPTNO NUMBER(2) PRIMARY KEY,
DNAME VARCHAR(13),
LOC VARCHAR(12)
);

DESC DEPT_TEST;

CREATE SEQUENCE DEPT_TEST_SEQ START WITH 10 INCREMENT BY 10;

INSERT INTO DEPT_TEST VALUES ( DEPT_TEST_SEQ.NEXTVAL, 'AA', 'KOR');
INSERT INTO DEPT_TEST VALUES ( DEPT_TEST_SEQ.NEXTVAL, 'BB', 'KOR2');
INSERT INTO DEPT_TEST VALUES ( DEPT_TEST_SEQ.NEXTVAL, 'CC', 'KOR3');
INSERT INTO DEPT_TEST VALUES ( DEPT_TEST_SEQ.NEXTVAL, 'DD', 'KOR4');

SELECT * FROM DEPT_TEST;

DROP SEQUENCE DEPT_TEST_SEQ;

