-- 1번
CREATE TABLE userinfo(
ID VARCHAR2(20) PRIMARY KEY,
PWD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL
);

DESC userinfo;

-- 2번
ALTER TABLE userinfo ADD EMAIL VARCHAR2(30) NULL;

SELECT * FROM userinfo;

-- 3번
INSERT INTO userinfo VALUES ('1', '1234', '홍길동', 'hong@it-kys.com');
INSERT INTO userinfo VALUES ('2', '1234', '이순신', 'lee@it-kys.com');
INSERT INTO userinfo VALUES ('3', '1234', '유관순', NULL);
INSERT INTO userinfo VALUES ('4', '1234', '신사임당', 'shin@it-kys.com');
INSERT INTO userinfo VALUES ('5', '1234', '김유신', '');

-- 4번
SELECT E.ENAME, D.DNAME, D.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.ENAME = 'SMITH';

-- 5번
SELECT *
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP', 'DEPT');

-- 6번
CREATE INDEX IND_TEST
ON EMP(ENAME);

-- 7번
GRANT CREATE VIEW TO SCOTT;

CREATE VIEW EMP_DEPTNO30
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP_DEPTNO30;

