-- 1번
/*
다운로드 위치 => C:\Users\Administrator\Desktop\DB수업
파일명 => Get Started With Oracle Database 11g Express Edition 
*/

-- 2번
CREATE USER TEST IDENTIFIED BY TEST;

GRANT CONNECT, RESOURCE TO TEST;

ALTER USER TEST DEFAULT TABLESPACE USERS;

ALTER USER TEST QUOTA UNLIMITED ON USERS;

-- 3번
CONN TEST/TEST;

-- 4번
CREATE TABLE MEMBER(
SEQ NUMBER(4),
ID VARCHAR2(16) PRIMARY KEY,
NAME VARCHAR2(20) NOT NULL,
AGE NUMBER(4),
HEIGHT NUMBER(10, 2),
LOGTIME DATE
);

-- 5번 
DESC MEMBER;

SELECT * FROM MEMBER;

-- 6번
CREATE SEQUENCE MEMBER_SEQ NOCACHE NOCYCLE;

-- 7번
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'TEST1', 'TEST_01', 32, 179.34, SYSDATE);
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'TEST2', 'TEST_02', 28, 181.88, SYSDATE);

SELECT * FROM MEMBER;

